"use client";
import SearchBar from "@/app/components/SearchBar";
import GroupTable from "@/app/components/Table";
import ReloadButton from "@/app/components/ReloadButton";
import PlusButton from "@/app/components/PlusButton";
import Modal from "@/app/components/Modal";
import FormTeacher, { TeacherData } from "@/app/components/FormTeacher";
import { fetchTeachers, addTeacher, updateTeacher, deleteTeacher } from "@/app/supabase/teacherActions";
import React, { useEffect, useState } from "react";

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [typeOfModal, setTypeOfModal] = useState("");
  const [functionToExecute, setFunctionToExecute] = useState<() => void>(() => () => {});
  const [actualInfo, setActualInfo] = useState<TeacherData>({
    teacherid: 0,
    firstname: "",
    lastname: "",
    email: "",
    phone: "",
  });
  const [rows, setRows] = useState<TeacherData[]>([]);
  const [filteredRows, setFilteredRows] = useState<TeacherData[]>([]);

  const handleInfoToModal = (info: TeacherData) => {
    setActualInfo(info);
  };

  const handleOpenModal = (action: boolean, type: string) => {
    setTypeOfModal(type);
    setIsModalOpen(action);
    
    // Reset actualInfo when creating new
    if (type === "new") {
      setActualInfo({
        teacherid: 0,
        firstname: "",
        lastname: "",
        email: "",
        phone: "",
      });
    }
    
    switch (type) {
      case "new":
        setFunctionToExecute(() => async (info: TeacherData) => {
          try {
            await addTeacher(info);
            const teachers = await fetchTeachers();
            setRows(teachers);
            setFilteredRows(teachers);
            setIsModalOpen(false);
          } catch (error) {
            console.error('Error al crear maestro:', error);
            alert('Error al crear el maestro. Verifica los datos.');
          }
        });
        break;
      case "edit":
        setFunctionToExecute(() => async (info: TeacherData) => {
          try {
            await updateTeacher(info);
            const teachers = await fetchTeachers();
            setRows(teachers);
            setFilteredRows(teachers);
            setIsModalOpen(false);
          } catch (error) {
            console.error('Error al actualizar maestro:', error);
            alert('Error al actualizar el maestro. Verifica los datos.');
          }
        });
        break;
      case "delete":
        setFunctionToExecute(() => async (info: TeacherData) => {
          try {
            if (info.teacherid != null) {
              await deleteTeacher(info.teacherid);
              const teachers = await fetchTeachers();
              setRows(teachers);
              setFilteredRows(teachers);
              setIsModalOpen(false);
            }
          } catch (error: unknown) {
            console.error('Error al eliminar maestro:', error);
            
            // El error puede venir como string serializado desde el servidor
            let errorString = '';
            if (error instanceof Error) {
              errorString = error.message;
            } else if (typeof error === 'string') {
              errorString = error;
            }
            
            // Verificar si contiene el código 23503 o menciona foreign key
            if (errorString.includes('23503') || errorString.includes('foreign key') || errorString.includes('violates')) {
              alert(
                '❌ No se puede eliminar este profesor\n\n' +
                '📋 Razón: El profesor está asignado a uno o más grupos activos\n\n' +
                '✅ Opciones para proceder:\n' +
                '1. Ve a "Grupos" y reasigna los grupos a otro profesor\n' +
                '2. Elimina los grupos del profesor primero\n' +
                '3. Marca al profesor como "inactivo" para mantener el historial\n\n' +
                '⚠️ Nota: Eliminar un profesor borrará su historial de cursos'
              );
            } else {
              alert('Error al eliminar el maestro.');
            }
          }
        });
        break;
      case "copy":
        setFunctionToExecute(() => async (info: TeacherData) => {
          try {
            const newTeacher = {
              ...info,
              teacherid: 0, // ID will be auto-generated by the database (excluded in addTeacher)
              firstname: info.firstname + " (Copia)",
            };
            await addTeacher(newTeacher);
            const teachers = await fetchTeachers();
            setRows(teachers);
            setFilteredRows(teachers);
            setIsModalOpen(false);
          } catch (error) {
            console.error('Error al copiar maestro:', error);
            alert('Error al copiar el maestro. Verifica los datos.');
          }
        });
        break;
    }
  };

  const headers = [
    "ID Maestro",
    "Nombres",
    "Apellidos",
    "Correo",
    "Teléfono",
    "Acciones",
  ];

  const loadTeachers = async () => {
    setRows([]);
    const teachers = await fetchTeachers();
    setRows(teachers);
    setFilteredRows(teachers);
  };

  useEffect(() => {
    loadTeachers();
  }, []);

  return (
    <>
      <div className="w-full flex h-fit justify-between ">
        <SearchBar 
          className="" 
          placeholder="Buscar maestro" 
          data={rows}
          onFilter={setFilteredRows}
        />
        <div className="flex gap-x-2 items-center ">
          <p className=" text-tangaroa-950 font-bold  ">Nuevo Maestro</p>
          <PlusButton OpenOnPlusModal={() => handleOpenModal(true, "new")} className=" "></PlusButton>
          <ReloadButton onClick={() => loadTeachers()} className=" "></ReloadButton>
        </div>
      </div>
      <div>
        {filteredRows.length === 0 ? (
          <div className="animate-pulse bg-gray-200 rounded-lg space-y-4 mt-10 h-22 w-full"></div>
        ) : (
          <GroupTable
            headers={headers}
            rows={filteredRows}
            OpenOnEditModal={() => handleOpenModal(true, "edit")}
            onEditButton={handleInfoToModal}
            OpenOnDeletetModal={() => handleOpenModal(true, "delete")}
            onCopyButton={(teacher) => {
              handleInfoToModal(teacher);
              handleOpenModal(true, "copy");
            }}
          />
        )}
        <Modal isOpen={isModalOpen} onClose={() => handleOpenModal(false, "edit")}>
          <FormTeacher
            data={actualInfo}
            onChange={setActualInfo}
            type={typeOfModal}
            functionToExecute={functionToExecute}
          />
        </Modal>
      </div>
    </>
  );
}
