"use client";
import SearchBar from "@/app/components/SearchBar";
import GroupTable from "@/app/components/Table";
import ReloadButton from "@/app/components/ReloadButton";
import PlusButton from "@/app/components/PlusButton";
import { StudentData } from "@/app/components/FormStudents";
import StudentFormEdit from "@/app/components/FormStudents";
import Modal from "@/app/components/Modal";
import {
  fetchStudents,
  addStudent,
  updateStudent,
  deleteStudent,
} from "@/app/supabase/studentActions";
import { getAcademicLevelText, getBiblicalKnowledgeText } from "@/app/utils/studentRatings";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [isModalOpen, setIsModalOpenEdit] = useState(false);
  const [typeOfModal, setTypeOfModal] = useState("");
  const [functionToExecute, setFunctionToExecute] = useState<() => void>(
    () => () => {}
  );

  const [actualInfo, setActualInfo] = useState<StudentData>({
    studentid: 0,
    firstname: "",
    lastname: "",
    email: "",
    phone: "",
    academicrating: 0,
    biblicalrating: 0,
    status: false,
  });
  const [rows, setRows] = useState<StudentData[]>([]);
  const [filteredRows, setFilteredRows] = useState<StudentData[]>([]);

  const handleInfoToModal = (info: StudentData) => {
    setActualInfo(info);
  };

  const handleOpenModal = (action: boolean, type: string) => {
    setTypeOfModal(type);
    setIsModalOpenEdit(action);
    
    // Reset actualInfo when creating new
    if (type === "new") {
      setActualInfo({
        studentid: 0,
        firstname: "",
        lastname: "",
        email: "",
        phone: "",
        academicrating: 0,
        biblicalrating: 0,
        status: false,
      });
    }
    
    switch (type) {
      case "new":
        setFunctionToExecute(() => async (info: StudentData) => {
          try {
            await addStudent(info);
            const students = await fetchStudents();
            setRows(students);
            setFilteredRows(students);
            setIsModalOpenEdit(false);
          } catch (error) {
            console.error('Error al crear estudiante:', error);
            alert('Error al crear el estudiante. Verifica los datos.');
          }
        });
        break;
      case "edit":
        setFunctionToExecute(() => async (info: StudentData) => {
          try {
            await updateStudent(info);
            const students = await fetchStudents();
            setRows(students);
            setFilteredRows(students);
            setIsModalOpenEdit(false);
          } catch (error) {
            console.error('Error al actualizar estudiante:', error);
            alert('Error al actualizar el estudiante. Verifica los datos.');
          }
        });
        break;
      case "delete":
        setFunctionToExecute(() => async (info: StudentData) => {
          try {
            await deleteStudent(info.studentid);
            const students = await fetchStudents();
            setRows(students);
            setFilteredRows(students);
            setIsModalOpenEdit(false);
          } catch (error: unknown) {
            console.error('Error al eliminar estudiante:', error);
            
            let errorString = '';
            if (error instanceof Error) {
              errorString = error.message;
            } else if (typeof error === 'string') {
              errorString = error;
            }
            
            if (errorString.includes('23503') || errorString.includes('foreign key') || errorString.includes('violates')) {
              alert(
                '❌ No se puede eliminar este estudiante\n\n' +
                '📋 Razón: El estudiante está inscrito en uno o más grupos\n\n' +
                '✅ Pasos para eliminar:\n' +
                '1. Ve a "Grupos"\n' +
                '2. Click en el ícono 👥 del grupo correspondiente\n' +
                '3. Desvincular al estudiante del grupo\n' +
                '4. Repite para todos los grupos donde esté inscrito\n' +
                '5. Ahora podrás eliminar al estudiante\n\n' +
                '💡 Alternativa: Marca como "inactivo" para mantener historial'
              );
            } else {
              alert('Error al eliminar el estudiante.');
            }
          }
        });
        break;
      case "copy":
        setFunctionToExecute(() => async (info: StudentData) => {
          try {
            const newStudent = {
              ...info,
              studentid: 0, // ID will be auto-generated by the database (excluded in addStudent)
              firstname: info.firstname + " (Copia)",
            };
            await addStudent(newStudent);
            const students = await fetchStudents();
            setRows(students);
            setFilteredRows(students);
            setIsModalOpenEdit(false);
          } catch (error) {
            console.error('Error al copiar estudiante:', error);
            alert('Error al copiar el estudiante. Verifica los datos.');
          }
        });
        break;
    }
  };

  const headers = [
    "ID Alumno",
    "Nombres",
    "Apellidos",
    "Correo",
    "Teléfono",
    "Nivel de Educación",
    "Conocimiento Bíblico",
    "Estado",
    "Acciones",
  ];
  const loadStudents = async () => {
    setRows([]); // Clear previous rows
    const students = await fetchStudents();
    setRows(students);
    setFilteredRows(students);
  };
  useEffect(() => {
    loadStudents();
  }, []);

  return (
    <>
      <div className="w-full flex h-fit justify-between ">
        <SearchBar 
          className="" 
          placeholder="Buscar estudiante"
          data={rows}
          onFilter={setFilteredRows}
        />
        <div className="flex gap-x-2 items-center ">
          <p className=" text-tangaroa-950 font-bold  ">Nuevo Estudiante</p>
          <PlusButton
            OpenOnPlusModal={() => handleOpenModal(true, "new")}
            className=" "
          ></PlusButton>
          <ReloadButton onClick={() => loadStudents()}></ReloadButton>
        </div>
      </div>
      
    
      
      <div>
        {filteredRows.length === 0 ? (
          // Skeleton loader
          <div className="animate-pulse bg-gray-200 rounded-lg space-y-4 mt-10 h-22 w-full"></div>
        ) : (
          <GroupTable
            headers={headers}
            rows={filteredRows.map(student => ({
              ...student,
              academicrating: getAcademicLevelText(student.academicrating),
              biblicalrating: getBiblicalKnowledgeText(student.biblicalrating)
            }))}
            OpenOnEditModal={() => {
              handleOpenModal(true, "edit");
            }}
            onEditButton={(displayStudent) => {
              // Encontrar el estudiante original con valores numéricos
              const originalStudent = filteredRows.find(s => s.studentid === (displayStudent as unknown as StudentData).studentid);
              if (originalStudent) {
                handleInfoToModal(originalStudent);
              }
            }}
            OpenOnDeletetModal={() => {
              handleOpenModal(true, "delete");
            }}
            onCopyButton={(displayStudent) => {
              // Encontrar el estudiante original con valores numéricos
              const originalStudent = filteredRows.find(s => s.studentid === (displayStudent as unknown as StudentData).studentid);
              if (originalStudent) {
                handleInfoToModal(originalStudent);
                handleOpenModal(true, "copy");
              }
            }}
          />
        )}
        <Modal
          isOpen={isModalOpen}
          onClose={() => handleOpenModal(false, "edit")}
        >
          <StudentFormEdit
            data={actualInfo}
            onChange={setActualInfo}
            type={typeOfModal}
            functionToExecute={functionToExecute}
          />
        </Modal>
      </div>
    </>
  );
}
