"use client";

import Cards from "@/app/components/Cards";
import CardPlusButton from "@/app/components/CardPlusButton";
import Modal from "@/app/components/Modal";
import FormManagerCourse from "@/app/components/FormManageCourse";
import { Course } from "@/app/components/FormManageCourse";
import React, { useState, useEffect } from "react";

import { fetchCourses, addCourse,updateCourse,deleteCourse } from "@/app/supabase/courseActions";

export default function Home() {
  const [isModalOpenEdit, setIsModalOpenEdit] = useState(false);
  const [typeOfModal, setTypeOfModal] = useState("");
  const [functionToExecute, setFunctionToExecute] = useState<() => void>(
    () => () => {}
  );

  const [actualInfo, setActualInfo] = useState<Course>({ courseid: undefined, coursename: "" });
   const [cards, setCard] = useState<Course[]>([]);
  const handleInfoToModal = (info: Course) => {
    setActualInfo(info);
    // Aquí podrías hacer un fetch o llamar a una función que haga la petición a tu API
  };

  const handleOpenModal = (action: boolean, type: string) => {
    setTypeOfModal(type);
    setIsModalOpenEdit(action);
    
    // Reset actualInfo when creating new
    if (type === "new") {
      setActualInfo({
        courseid: 0,
        coursename: "",
      });
    }
    
    switch (type) {
      case "new":
        setFunctionToExecute(() => async (info: Course) => {
          try {
            await addCourse(info);
            const courses = await fetchCourses();
            setCard(courses);
            setIsModalOpenEdit(false);
          } catch (error) {
            console.error('Error al crear curso:', error);
            alert('Error al crear el curso. Verifica los datos.');
          }
        });
        break;
      case "edit":
        setFunctionToExecute(() => async (info: Course) => {
          try {
            await updateCourse(info);
            const courses = await fetchCourses();
            setCard(courses);
            setIsModalOpenEdit(false);
          } catch (error) {
            console.error('Error al actualizar curso:', error);
            alert('Error al actualizar el curso. Verifica los datos.');
          }
        });
        break;
      case "delete":
        setFunctionToExecute(() => async (info: Course) => {
          try {
            await deleteCourse(info.courseid || 0);
            const courses = await fetchCourses();
            setCard(courses);
            setIsModalOpenEdit(false);
          } catch (error: unknown) {
            console.error('Error al eliminar curso:', error);
            
            let errorString = '';
            if (error instanceof Error) {
              errorString = error.message;
            } else if (typeof error === 'string') {
              errorString = error;
            }
            
            if (errorString.includes('23503') || errorString.includes('foreign key') || errorString.includes('violates')) {
              alert(
                '❌ No se puede eliminar este curso\n\n' +
                '📋 Razón: El curso está asignado a grupos activos o tiene profesores asignados\n\n' +
                '✅ Pasos para eliminar:\n' +
                '1. Ve a "Grupos" y elimina o reasigna grupos que usen este curso\n' +
                '2. Verifica que no haya profesores asignados a este curso\n' +
                '3. Ahora podrás eliminar el curso\n\n' +
                '💡 Recomendación: En lugar de eliminar, marca como "inactivo"\n' +
                '   Esto mantiene el historial de grupos y estudiantes pasados'
              );
            } else {
              alert('Error al eliminar el curso.');
            }
          }
        });
        break;
      case "copy":
        setFunctionToExecute(() => async (info: Course) => {
          try {
            const newCourse = {
              ...info,
              courseid: 0, // Set to 0 but will be excluded by addCourse (auto-generated by database)
              coursename: info.coursename + " (Copia)",
            };
            await addCourse(newCourse);
            const courses = await fetchCourses();
            setCard(courses);
            setIsModalOpenEdit(false);
          } catch (error) {
            console.error('Error al copiar curso:', error);
            alert('Error al copiar el curso. Verifica los datos.');
          }
        });
        break;
    }
  };
  const loadCourses = async () => {
      setCard([]); // Clear previous cards
      const courses = await fetchCourses();
      setCard(courses);
    };
    useEffect(() => {
      loadCourses();
    }, []);

  return (
    <div className="p-10 flex flex-wrap gap-6">
      {cards.map((item, index) => (
        <Cards
          OpenOnEditModal={() => {
            handleOpenModal(true, "edit");
          }}
          onEditButton={() => handleInfoToModal({ courseid: item.courseid, coursename: item.coursename })}
          OpenOnDeletetModal={() => {
            handleOpenModal(true, "delete");
          }}
          onCopyButton={() => handleInfoToModal({ courseid: item.courseid, coursename: item.coursename })}
          OpenOnCopyModal={() => handleOpenModal(true, "copy")}
          key={index}
          label={`${item.coursename}`}
          data={[
            // { label: "Grupos Activos", value: item.activeGroups },
            // { label: "Maestros Libres", value: item.availableTeachers },
            // { label: "Designación", value: item.designation },
            // { label: "Estudiantes inscritos", value: item.enrolledStudents },
          ]}
        />
      ))}

      <CardPlusButton
        OpenOnPlusModal={() => handleOpenModal(true, "new")}
      ></CardPlusButton>

      <Modal
        isOpen={isModalOpenEdit}
        onClose={() => handleOpenModal(false, "edit")}
      >
        <FormManagerCourse
          data={actualInfo}
          onChange={setActualInfo}
          type={typeOfModal}
          functionToExecute={functionToExecute}
        ></FormManagerCourse>
      </Modal>
    </div>
  );
}
